name: Docker-CI/CD
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
jobs:
  login-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@master
      


